//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinalProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _15ef37fc_6f87_47e0_9128_201a9403847f {
            get {
                object obj = ResourceManager.GetObject("15ef37fc-6f87-47e0-9128-201a9403847f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _15ef37fc_6f87_47e0_9128_201a9403847f_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("15ef37fc-6f87-47e0-9128-201a9403847f-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _15ef37fc_6f87_47e0_9128_201a9403847f_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("15ef37fc-6f87-47e0-9128-201a9403847f-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _248132e3_0cf2_4b4a_9ef6_8fa67201a7cc {
            get {
                object obj = ResourceManager.GetObject("248132e3-0cf2-4b4a-9ef6-8fa67201a7cc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2fcc8f2c_d375_4127_b8e3_4ef594da0624 {
            get {
                object obj = ResourceManager.GetObject("2fcc8f2c-d375-4127-b8e3-4ef594da0624", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2fcc8f2c_d375_4127_b8e3_4ef594da0624_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("2fcc8f2c-d375-4127-b8e3-4ef594da0624-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _31a44358_f08d_4fe4_b036_fbc19e6016d6_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("31a44358-f08d-4fe4-b036-fbc19e6016d6-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _31a44358_f08d_4fe4_b036_fbc19e6016d6_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("31a44358-f08d-4fe4-b036-fbc19e6016d6-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5569e17d_6e15_4d4b_8918_8e35bcebb444 {
            get {
                object obj = ResourceManager.GetObject("5569e17d-6e15-4d4b-8918-8e35bcebb444", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9bb05e7b_bebe_45a4_8401_a189a9a4f5f3 {
            get {
                object obj = ResourceManager.GetObject("9bb05e7b-bebe-45a4-8401-a189a9a4f5f3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bd5ad008_ab6d_4842_b59b_6d43d8564f91 {
            get {
                object obj = ResourceManager.GetObject("bd5ad008-ab6d-4842-b59b-6d43d8564f91", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bd5ad008_ab6d_4842_b59b_6d43d8564f911 {
            get {
                object obj = ResourceManager.GetObject("bd5ad008-ab6d-4842-b59b-6d43d8564f911", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
